"""Update Plant model

Revision ID: 3d949ffe5e93
Revises: 1fbfa43fdc29
Create Date: 2026-02-21 23:03:53.658304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d949ffe5e93'
down_revision = '1fbfa43fdc29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('plants', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('plants', 'image',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('plants', 'price',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('plants', 'is_in_stock',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('plants', 'is_in_stock',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('plants', 'price',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('plants', 'image',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('plants', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
